sudo: false
language: rust
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libssl-dev

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
    - rust: nightly

script:
 - cargo build
 - cargo test

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh);
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID;
  fi
