sudo: false
language: rust
# Dependencies of kcov, used by coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake


rust:
- stable
- beta

before_install:
- |
  cargo install cargo-travis &&
  export PATH=$HOME/.cargo/bin:$PATH
  
script:
- |
  cargo build &&
  cargo test &&
  cargo bench

after_success:
- cargo coveralls
