[package]

name = "imap"
version = "0.9.3"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>",
           "Jon Gjengset <jon@thesquareplanet.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/mattnenterprise/rust-imap"
homepage = "https://github.com/mattnenterprise/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
travis-ci = { repository = "mattnenterprise/rust-imap" }
appveyor = { repository = "mattnenterprise/rust-imap", branch = "master", service = "github" }
coveralls = { repository = "mattnenterprise/rust-imap", branch = "master", service = "github" }
maintenance = { status = "passively-maintained" }

[lib]
name = "imap"
path = "src/lib.rs"

[dependencies]
native-tls = "0.2.2"
regex = "1.0"
bufstream = "0.1"
imap-proto = "0.6"
nom = "4.0"
base64 = "0.10"

[dev-dependencies]
lettre = "0.9"
lettre_email = "0.9"

[patch.crates-io]
lettre = { git = "https://github.com/lettre/lettre.git" }
lettre_email = { git = "https://github.com/lettre/lettre.git" }
