[package]

name = "imap"
version = "0.6.0"
authors = ["Matt McCoy <mattnenterprise@yahoo.com>",
           "Jon Gjengset <jon@thesquareplanet.com>"]
documentation = "https://docs.rs/imap/"
repository = "https://github.com/mattnenterprise/rust-imap"
homepage = "https://github.com/mattnenterprise/rust-imap"
description = "IMAP client for Rust"
readme = "README.md"
license = "Apache-2.0/MIT"

keywords = ["email", "imap"]
categories = ["email", "network-programming"]

[badges]
travis-ci = { repository = "mattnenterprise/rust-imap" }
appveyor = { repository = "mattnenterprise/rust-imap", branch = "master", service = "github" }
coveralls = { repository = "mattnenterprise/rust-imap", branch = "master", service = "github" }
maintenance = { status = "passively-maintained" }

[lib]
name = "imap"
path = "src/lib.rs"

[dependencies]
native-tls = "0.1"
regex = "0.2"
bufstream = "0.1"
#imap-proto = "0.1"
imap-proto = { git = "https://github.com/djc/imap-proto.git" }
nom = "3.2.1"

[dev-dependencies]
base64 = "0.7"
